webtalk_init -webtalk_dir D:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.sim/sim_1/behav/xsim/xsim.dir/pwmBlock_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 19 23:23:08 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "73ccae7e-784a-46db-b16c-998ba6d91df8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e11cfa73976b4dbfb3e45702d921c37b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "102624720 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2362486271 -regid "" -xml D:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.sim/sim_1/behav/xsim/xsim.dir/pwmBlock_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.sim/sim_1/behav/xsim/xsim.dir/pwmBlock_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.sim/sim_1/behav/xsim/xsim.dir/pwmBlock_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
