# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ESIFTask2_1_bd/ESIFTask2_1_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd || ORIG_REF_NAME==ESIFTask2_1_bd} -quiet] -quiet

# IP: bd/ESIFTask2_1_bd/ip/ESIFTask2_1_bd_processing_system7_0_0/ESIFTask2_1_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd_processing_system7_0_0 || ORIG_REF_NAME==ESIFTask2_1_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/ESIFTask2_1_bd/ip/ESIFTask2_1_bd_axi_gpio_0_0/ESIFTask2_1_bd_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd_axi_gpio_0_0 || ORIG_REF_NAME==ESIFTask2_1_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ESIFTask2_1_bd/ip/ESIFTask2_1_bd_auto_pc_0/ESIFTask2_1_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd_auto_pc_0 || ORIG_REF_NAME==ESIFTask2_1_bd_auto_pc_0} -quiet] -quiet

# IP: bd/ESIFTask2_1_bd/ip/ESIFTask2_1_bd_ps7_0_axi_periph_0/ESIFTask2_1_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==ESIFTask2_1_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ESIFTask2_1_bd/ip/ESIFTask2_1_bd_rst_ps7_0_100M_0/ESIFTask2_1_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ESIFTask2_1_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==ESIFTask2_1_bd_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/ESIFTask2_1_bd/ESIFTask2_1_bd_ooc.xdc
