# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.srcs/sources_1/bd/ESIFTask2_2_bd/ip/ESIFTask2_2_bd_auto_pc_0/ESIFTask2_2_bd_auto_pc_0.xci
# IP: The module: 'ESIFTask2_2_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.srcs/sources_1/bd/ESIFTask2_2_bd/ip/ESIFTask2_2_bd_auto_pc_0/ESIFTask2_2_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ESIFTask2_2_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.srcs/sources_1/bd/ESIFTask2_2_bd/ip/ESIFTask2_2_bd_auto_pc_0/ESIFTask2_2_bd_auto_pc_0.xci
# IP: The module: 'ESIFTask2_2_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DEV/ESIF/Task2/ESIF_Task2/Subtask2/ESIFTask2_2.srcs/sources_1/bd/ESIFTask2_2_bd/ip/ESIFTask2_2_bd_auto_pc_0/ESIFTask2_2_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ESIFTask2_2_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
